### ISSUE TITLE
训练过程中遇到的问题

### ISSUE THREAD

**Issue by FZfangzheng** [theonegis/edcstfn#2]
作者您好，我尝试使用您的代码进行训练，但是效果似乎不是很好。我采用的参数是run.py文件开头给出的建议参数，不同之处在于根据我训练集图片大小改动了切块的大小。预训练模型的自编码器训练了30个epoch。在EDCSTFN的训练结果来看loss长时间稳定E-4，训练准确性长时间稳定E-6。验证结果来看，RMSE=6~10，ERGAS=3.4，SAM=1.3，这些似乎比论文中提到的大不少。我尝试修改学习率，做归一化处理，但是没有好转。所以我才向作者请教，作者若有空能给予一些帮助？谢谢

**Comment by theonegis** [comment]
The code has been updated, please download the latest version. This is because many versions were coexisting when I performed the experiments and I mistakenly uploaded the wrong version of the source code in the last.

**Comment by theonegis** [comment]
@FZfangzheng If there are any problems, please let me know. You can also write emails to me.

**Comment by theonegis** [comment]
The code has been updated, please download the latest version. If there are any other problems, please feel free to contact me or make a pull request.
