### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by yisun98** [theonegis/edcstfn#5]

**Comment by wangtaocs** [comment]
您好,我目前也在对您的工作进行研究,希望能够复现您的工作,希望能得到您的数据集(965929275@qq.com),谢谢您的帮助!

**Comment by book7** [comment]
您好,我目前也在对您的工作进行研究,希望能够复现您的工作,希望能得到您的数据集(1809785095@qq.com),谢谢您的帮助!

**Comment by JerryHuangRJH** [comment]
您好,我目前也在对您的工作进行研究,希望能够复现您的工作,希望能得到您的数据集(635108310@qq.com),谢谢您的帮助!

**Comment by veselius** [comment]
您好，我对您的工作非常感兴趣，请问您是否可以提供您时空融合的数据集给我呢（[1957240687@qq.com]（mailto：veselius@163.com）），十分感谢！

**Comment by veselius** [comment]
您好，我对您的工作非常感兴趣，请问您是否可以提供您时空融合的数据集给我呢（veselius@163.com），不胜感激！

**Comment by yisun98** [comment]
> _No description provided._
